In [1]:
import pandas as pd
import numpy as np

In [2]:
tb = pd.read_csv('cdc_tuberculosis.csv')
tb

,Unnamed: 0,No. of TB cases,Unnamed: 2,Unnamed: 3,TB incidence,Unnamed: 5,Unnamed: 6
0,U.S. jurisdiction,2019,2020,2021,2019.00,2020.00,2021.00
1,Total,"8,900","7,173","7,860",2.71,2.16,2.37
2,Alabama,87,72,92,1.77,1.43,1.83
3,Alaska,58,58,58,7.91,7.92,7.92
4,Arizona,183,136,129,2.51,1.89,1.77
5,Arkansas,64,59,69,2.12,1.96,2.28
6,California,"2,111","1,706","1,750",5.35,4.32,4.46
7,Colorado,66,52,58,1.15,0.90,1.00
8,Connecticut,67,54,54,1.88,1.50,1.50
9,Delaware,18,17,43,1.84,1.71,4.29
10,District of Columbia,24,19,19,3.39,2.75,2.84
11,Florida,558,412,499,2.60,1.91,2.29
12,Georgia,302,221,228,2.84,2.06,2.11
13,Hawaii,99,92,106,6.99,6.34,7.35
14,Idaho,7,8,4,0.39,0.43,0.21
15,Illinois,326,216,255,2.57,1.69,2.01
16,Indiana,108,92,127,1.60,1.36,1.87
17,Iowa,52,39,49,1.65,1.22,1.53
18,Kansas,37,37,43,1.27,1.26,1.47
19,Kentucky,66,67,57,1.48,1.49,1.26
20,Louisiana,88,99,86,1.89,2.13,1.86
21,Maine,18,17,14,1.34,1.25,1.02
22,Maryland,209,148,192,3.45,2.40,3.11
23,Massachusetts,178,142,151,2.58,2.02,2.16
24,Michigan,131,101,136,1.31,1.00,1.35
25,Minnesota,148,117,134,2.62,2.05,2.35
26,Mississippi,58,41,45,1.95,1.39,1.53
27,Missouri,70,79,77,1.14,1.28,1.25
28,Montana,2,4,3,0.19,0.37,0.27
29,Nebraska,17,33,22,0.88,1.68,1.12
30,Nevada,53,57,61,1.71,1.83,1.94
31,New Hampshire,6,12,12,0.44,0.87,0.86
32,New Jersey,310,245,279,3.49,2.64,3.01
33,New Mexico,41,29,24,1.95,1.37,1.13
34,New York,746,605,681,3.83,3.00,3.43
35,North Carolina,185,159,178,1.76,1.52,1.69
36,North Dakota,18,10,15,2.36,1.28,1.94
37,Ohio,150,130,149,1.28,1.10,1.26
38,Oklahoma,73,67,69,1.84,1.69,1.73
39,Oregon,70,67,78,1.66,1.58,1.84
40,Pennsylvania,199,156,166,1.55,1.20,1.28
41,Rhode Island,14,7,17,1.32,0.64,1.55
42,South Carolina,80,67,88,1.55,1.31,1.70
43,South Dakota,16,16,12,1.80,1.80,1.34
44,Tennessee,129,113,85,1.89,1.63,1.22
45,Texas,"1,154",883,991,3.98,3.02,3.36
46,Utah,27,29,17,0.84,0.88,0.51
47,Vermont,4,3,2,0.64,0.47,0.31
48,Virginia,191,169,161,2.23,1.96,1.86
49,Washington,221,163,199,2.90,2.11,2.57
50,West Virginia,9,13,7,0.50,0.73,0.39
51,Wisconsin,51,35,66,0.88,0.59,1.12
52,Wyoming,1,0,3,0.17,0.00,0.52

In [3]:
tb = pd.read_csv('cdc_tuberculosis.csv',header=1)
tb

       U.S. jurisdiction   2019   2020   2021  2019.1  2020.1  2021.1
0                  Total  8,900  7,173  7,860    2.71    2.16    2.37
1                Alabama     87     72     92    1.77    1.43    1.83
2                 Alaska     58     58     58    7.91    7.92    7.92
3                Arizona    183    136    129    2.51    1.89    1.77
4               Arkansas     64     59     69    2.12    1.96    2.28
5             California  2,111  1,706  1,750    5.35    4.32    4.46
6               Colorado     66     52     58    1.15    0.90    1.00
7            Connecticut     67     54     54    1.88    1.50    1.50
8               Delaware     18     17     43    1.84    1.71    4.29
9   District of Columbia     24     19     19    3.39    2.75    2.84
10               Florida    558    412    499    2.60    1.91    2.29
11               Georgia    302    221    228    2.84    2.06    2.11
12                Hawaii     99     92    106    6.99    6.34    7.35
13                 Idaho      7      8      4    0.39    0.43    0.21
14              Illinois    326    216    255    2.57    1.69    2.01
15               Indiana    108     92    127    1.60    1.36    1.87
16                  Iowa     52     39     49    1.65    1.22    1.53
17                Kansas     37     37     43    1.27    1.26    1.47
18              Kentucky     66     67     57    1.48    1.49    1.26
19             Louisiana     88     99     86    1.89    2.13    1.86
20                 Maine     18     17     14    1.34    1.25    1.02
21              Maryland    209    148    192    3.45    2.40    3.11
22         Massachusetts    178    142    151    2.58    2.02    2.16
23              Michigan    131    101    136    1.31    1.00    1.35
24             Minnesota    148    117    134    2.62    2.05    2.35
25           Mississippi     58     41     45    1.95    1.39    1.53
26              Missouri     70     79     77    1.14    1.28    1.25
27               Montana      2      4      3    0.19    0.37    0.27
28              Nebraska     17     33     22    0.88    1.68    1.12
29                Nevada     53     57     61    1.71    1.83    1.94
30         New Hampshire      6     12     12    0.44    0.87    0.86
31            New Jersey    310    245    279    3.49    2.64    3.01
32            New Mexico     41     29     24    1.95    1.37    1.13
33              New York    746    605    681    3.83    3.00    3.43
34        North Carolina    185    159    178    1.76    1.52    1.69
35          North Dakota     18     10     15    2.36    1.28    1.94
36                  Ohio    150    130    149    1.28    1.10    1.26
37              Oklahoma     73     67     69    1.84    1.69    1.73
38                Oregon     70     67     78    1.66    1.58    1.84
39          Pennsylvania    199    156    166    1.55    1.20    1.28
40          Rhode Island     14      7     17    1.32    0.64    1.55
41        South Carolina     80     67     88    1.55    1.31    1.70
42          South Dakota     16     16     12    1.80    1.80    1.34
43             Tennessee    129    113     85    1.89    1.63    1.22
44                 Texas  1,154    883    991    3.98    3.02    3.36
45                  Utah     27     29     17    0.84    0.88    0.51
46               Vermont      4      3      2    0.64    0.47    0.31
47              Virginia    191    169    161    2.23    1.96    1.86
48            Washington    221    163    199    2.90    2.11    2.57
49         West Virginia      9     13      7    0.50    0.73    0.39
50             Wisconsin     51     35     66    0.88    0.59    1.12
51               Wyoming      1      0      3    0.17    0.00    0.52

In [4]:
rename_dict = {'2019':'TB case 2019',
               '2020':'TB case 2020',
               '2021':'TB case 2021',
               '2019.1':'TB incidence 2019',
               '2020.1':'TB incidence 2020',
               '2021.1':'TB incidence 2021'            
}
tb = tb.rename(columns=rename_dict)
tb

,U.S. jurisdiction,TB case 2019,TB case 2020,TB case 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
0,Total,"8,900","7,173","7,860",2.71,2.16,2.37
1,Alabama,87,72,92,1.77,1.43,1.83
2,Alaska,58,58,58,7.91,7.92,7.92
3,Arizona,183,136,129,2.51,1.89,1.77
4,Arkansas,64,59,69,2.12,1.96,2.28
5,California,"2,111","1,706","1,750",5.35,4.32,4.46
6,Colorado,66,52,58,1.15,0.90,1.00
7,Connecticut,67,54,54,1.88,1.50,1.50
8,Delaware,18,17,43,1.84,1.71,4.29
9,District of Columbia,24,19,19,3.39,2.75,2.84
10,Florida,558,412,499,2.60,1.91,2.29
11,Georgia,302,221,228,2.84,2.06,2.11
12,Hawaii,99,92,106,6.99,6.34,7.35
13,Idaho,7,8,4,0.39,0.43,0.21
14,Illinois,326,216,255,2.57,1.69,2.01
15,Indiana,108,92,127,1.60,1.36,1.87
16,Iowa,52,39,49,1.65,1.22,1.53
17,Kansas,37,37,43,1.27,1.26,1.47
18,Kentucky,66,67,57,1.48,1.49,1.26
19,Louisiana,88,99,86,1.89,2.13,1.86
20,Maine,18,17,14,1.34,1.25,1.02
21,Maryland,209,148,192,3.45,2.40,3.11
22,Massachusetts,178,142,151,2.58,2.02,2.16
23,Michigan,131,101,136,1.31,1.00,1.35
24,Minnesota,148,117,134,2.62,2.05,2.35
25,Mississippi,58,41,45,1.95,1.39,1.53
26,Missouri,70,79,77,1.14,1.28,1.25
27,Montana,2,4,3,0.19,0.37,0.27
28,Nebraska,17,33,22,0.88,1.68,1.12
29,Nevada,53,57,61,1.71,1.83,1.94
30,New Hampshire,6,12,12,0.44,0.87,0.86
31,New Jersey,310,245,279,3.49,2.64,3.01
32,New Mexico,41,29,24,1.95,1.37,1.13
33,New York,746,605,681,3.83,3.00,3.43
34,North Carolina,185,159,178,1.76,1.52,1.69
35,North Dakota,18,10,15,2.36,1.28,1.94
36,Ohio,150,130,149,1.28,1.10,1.26
37,Oklahoma,73,67,69,1.84,1.69,1.73
38,Oregon,70,67,78,1.66,1.58,1.84
39,Pennsylvania,199,156,166,1.55,1.20,1.28
40,Rhode Island,14,7,17,1.32,0.64,1.55
41,South Carolina,80,67,88,1.55,1.31,1.70
42,South Dakota,16,16,12,1.80,1.80,1.34
43,Tennessee,129,113,85,1.89,1.63,1.22
44,Texas,"1,154",883,991,3.98,3.02,3.36
45,Utah,27,29,17,0.84,0.88,0.51
46,Vermont,4,3,2,0.64,0.47,0.31
47,Virginia,191,169,161,2.23,1.96,1.86
48,Washington,221,163,199,2.90,2.11,2.57
49,West Virginia,9,13,7,0.50,0.73,0.39
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

In [5]:
tb.sum(axis=0)

U.S. jurisdiction    TotalAlabamaAlaskaArizonaArkansasCaliforniaCol...
TB case 2019         8,9008758183642,111666718245583029973261085237...
TB case 2020         7,1737258136591,706525417194122219282169239376...
TB case 2021         7,8609258129691,750585443194992281064255127494...
TB incidence 2019                                               109.94
TB incidence 2020                                                93.09
TB incidence 2021                                               102.94
dtype: object

In [6]:
tb.dtypes

U.S. jurisdiction     object
TB case 2019          object
TB case 2020          object
TB case 2021          object
TB incidence 2019    float64
TB incidence 2020    float64
TB incidence 2021    float64
dtype: object

In [18]:
tb =(pd.read_csv('cdc_tuberculosis.csv',header=1,thousands=',')
    .rename(columns=rename_dict)
)
tb

,U.S. jurisdiction,TB case 2019,TB case 2020,TB case 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021
0,Total,8900,7173,7860,2.71,2.16,2.37
1,Alabama,87,72,92,1.77,1.43,1.83
2,Alaska,58,58,58,7.91,7.92,7.92
3,Arizona,183,136,129,2.51,1.89,1.77
4,Arkansas,64,59,69,2.12,1.96,2.28
5,California,2111,1706,1750,5.35,4.32,4.46
6,Colorado,66,52,58,1.15,0.90,1.00
7,Connecticut,67,54,54,1.88,1.50,1.50
8,Delaware,18,17,43,1.84,1.71,4.29
9,District of Columbia,24,19,19,3.39,2.75,2.84
10,Florida,558,412,499,2.60,1.91,2.29
11,Georgia,302,221,228,2.84,2.06,2.11
12,Hawaii,99,92,106,6.99,6.34,7.35
13,Idaho,7,8,4,0.39,0.43,0.21
14,Illinois,326,216,255,2.57,1.69,2.01
15,Indiana,108,92,127,1.60,1.36,1.87
16,Iowa,52,39,49,1.65,1.22,1.53
17,Kansas,37,37,43,1.27,1.26,1.47
18,Kentucky,66,67,57,1.48,1.49,1.26
19,Louisiana,88,99,86,1.89,2.13,1.86
20,Maine,18,17,14,1.34,1.25,1.02
21,Maryland,209,148,192,3.45,2.40,3.11
22,Massachusetts,178,142,151,2.58,2.02,2.16
23,Michigan,131,101,136,1.31,1.00,1.35
24,Minnesota,148,117,134,2.62,2.05,2.35
25,Mississippi,58,41,45,1.95,1.39,1.53
26,Missouri,70,79,77,1.14,1.28,1.25
27,Montana,2,4,3,0.19,0.37,0.27
28,Nebraska,17,33,22,0.88,1.68,1.12
29,Nevada,53,57,61,1.71,1.83,1.94
30,New Hampshire,6,12,12,0.44,0.87,0.86
31,New Jersey,310,245,279,3.49,2.64,3.01
32,New Mexico,41,29,24,1.95,1.37,1.13
33,New York,746,605,681,3.83,3.00,3.43
34,North Carolina,185,159,178,1.76,1.52,1.69
35,North Dakota,18,10,15,2.36,1.28,1.94
36,Ohio,150,130,149,1.28,1.10,1.26
37,Oklahoma,73,67,69,1.84,1.69,1.73
38,Oregon,70,67,78,1.66,1.58,1.84
39,Pennsylvania,199,156,166,1.55,1.20,1.28
40,Rhode Island,14,7,17,1.32,0.64,1.55
41,South Carolina,80,67,88,1.55,1.31,1.70
42,South Dakota,16,16,12,1.80,1.80,1.34
43,Tennessee,129,113,85,1.89,1.63,1.22
44,Texas,1154,883,991,3.98,3.02,3.36
45,Utah,27,29,17,0.84,0.88,0.51
46,Vermont,4,3,2,0.64,0.47,0.31
47,Virginia,191,169,161,2.23,1.96,1.86
48,Washington,221,163,199,2.90,2.11,2.57
49,West Virginia,9,13,7,0.50,0.73,0.39
50,Wisconsin,51,35,66,0.88,0.59,1.12
51,Wyoming,1,0,3,0.17,0.00,0.52

In [20]:
tb.dtypes

U.S. jurisdiction     object
TB case 2019           int64
TB case 2020           int64
TB case 2021           int64
TB incidence 2019    float64
TB incidence 2020    float64
TB incidence 2021    float64
dtype: object

In [21]:
tb.sum()

U.S. jurisdiction    TotalAlabamaAlaskaArizonaArkansasCaliforniaCol...
TB case 2019                                                     17800
TB case 2020                                                     14346
TB case 2021                                                     15720
TB incidence 2019                                               109.94
TB incidence 2020                                                93.09
TB incidence 2021                                               102.94
dtype: object

In [22]:
nst2019 = pd.read_csv('nst-est2019-01.csv')
nst2019

,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geographic Area,"April 1, 2010",NaN,Population Estimate (as of July 1),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
3,United States,"308,745,538","308,758,105","309,321,666","311,556,874","313,830,990","315,993,715","318,301,008","320,635,163","322,941,311","324,985,539","326,687,501","328,239,523"
4,Northeast,"55,317,240","55,318,443","55,380,134","55,604,223","55,775,216","55,901,806","56,006,011","56,034,684","56,042,330","56,059,240","56,046,620","55,982,803"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,Note: The estimates are based on the 2010 Cens...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Suggested Citation:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Release Date: December 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
nst2019 = pd.read_csv('nst-est2019-01.csv',header=3)
nst2019

,Unnamed: 0,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,"308,745,538","308,758,105","309,321,666","311,556,874","313,830,990","315,993,715","318,301,008","320,635,163","322,941,311","324,985,539","326,687,501","328,239,523"
1,Northeast,"55,317,240","55,318,443","55,380,134","55,604,223","55,775,216","55,901,806","56,006,011","56,034,684","56,042,330","56,059,240","56,046,620","55,982,803"
2,Midwest,"66,927,001","66,929,725","66,974,416","67,157,800","67,336,743","67,560,379","67,745,167","67,860,583","67,987,540","68,126,781","68,236,628","68,329,004"
3,South,"114,555,744","114,563,030","114,866,680","116,006,522","117,241,208","118,364,400","119,624,037","120,997,341","122,351,760","123,542,189","124,569,433","125,580,448"
4,West,"71,945,553","71,946,907","72,100,436","72,788,329","73,477,823","74,167,130","74,925,793","75,742,555","76,559,681","77,257,329","77,834,820","78,347,268"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Note: The estimates are based on the 2010 Cens...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Suggested Citation:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Release Date: December 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
nst2019 = pd.read_csv('nst-est2019-01.csv',header=3,thousands=',').rename(columns={"Unnamed: 0": "Geographic Area"})
nst2019

,Geographic Area,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,308745538.0,308758105.0,309321666.0,311556874.0,313830990.0,315993715.0,318301008.0,320635163.0,322941311.0,324985539.0,326687501.0,328239523.0
1,Northeast,55317240.0,55318443.0,55380134.0,55604223.0,55775216.0,55901806.0,56006011.0,56034684.0,56042330.0,56059240.0,56046620.0,55982803.0
2,Midwest,66927001.0,66929725.0,66974416.0,67157800.0,67336743.0,67560379.0,67745167.0,67860583.0,67987540.0,68126781.0,68236628.0,68329004.0
3,South,114555744.0,114563030.0,114866680.0,116006522.0,117241208.0,118364400.0,119624037.0,120997341.0,122351760.0,123542189.0,124569433.0,125580448.0
4,West,71945553.0,71946907.0,72100436.0,72788329.0,73477823.0,74167130.0,74925793.0,75742555.0,76559681.0,77257329.0,77834820.0,78347268.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Note: The estimates are based on the 2010 Cens...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Suggested Citation:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Release Date: December 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
nst2019['Geographic Area']=nst2019['Geographic Area'].str.strip('.')

In [31]:
nst2020 = pd.read_csv('NST-EST2022-POP.csv')
nst2020

,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Annual Estimates of the Resident Population fo...,NaN,NaN,NaN,NaN
1,Geographic Area,"April 1, 2020 Estimates Base",Population Estimate (as of July 1),NaN,NaN
2,NaN,NaN,2020,2021,2022
3,United States,"331,449,520","331,511,512","332,031,554","333,287,557"
4,Northeast,"57,609,156","57,448,898","57,259,257","57,040,406"
...,...,...,...,...,...
61,Note: The estimates are developed from a base ...,NaN,NaN,NaN,NaN
62,Suggested Citation:,NaN,NaN,NaN,NaN
63,Annual Estimates of the Resident Population fo...,NaN,NaN,NaN,NaN
64,"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN,NaN
65,Release Date: December 2022,NaN,NaN,NaN,NaN

In [38]:
nst2020=pd.read_csv('nst-est2019-01.csv',header=3,thousands=',').rename(columns={"Unnamed: 0": "Geographic Area"})
nst2020

,Geographic Area,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,United States,308745538.0,308758105.0,309321666.0,311556874.0,313830990.0,315993715.0,318301008.0,320635163.0,322941311.0,324985539.0,326687501.0,328239523.0
1,Northeast,55317240.0,55318443.0,55380134.0,55604223.0,55775216.0,55901806.0,56006011.0,56034684.0,56042330.0,56059240.0,56046620.0,55982803.0
2,Midwest,66927001.0,66929725.0,66974416.0,67157800.0,67336743.0,67560379.0,67745167.0,67860583.0,67987540.0,68126781.0,68236628.0,68329004.0
3,South,114555744.0,114563030.0,114866680.0,116006522.0,117241208.0,118364400.0,119624037.0,120997341.0,122351760.0,123542189.0,124569433.0,125580448.0
4,West,71945553.0,71946907.0,72100436.0,72788329.0,73477823.0,74167130.0,74925793.0,75742555.0,76559681.0,77257329.0,77834820.0,78347268.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Note: The estimates are based on the 2010 Cens...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Suggested Citation:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,"Source: U.S. Census Bureau, Population Division",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,Release Date: December 2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
nst2020['Geographic Area']=nst2020['Geographic Area'].str.strip('.')

In [41]:
td_marge = (
      tb.merge(right=nst2019,left_on='U.S. jurisdiction',right_on='Geographic Area')
    .merge(right=nst2020,left_on='U.S. jurisdiction',right_on='Geographic Area')
)
td_marge

,U.S. jurisdiction,TB case 2019,TB case 2020,TB case 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,Geographic Area_x,Census_x,Estimates Base_x,...,2010_y,2011_y,2012_y,2013_y,2014_y,2015_y,2016_y,2017_y,2018_y,2019_y
0,Alabama,87,72,92,1.77,1.43,1.83,Alabama,4779736.0,4780125.0,...,4785437.0,4799069.0,4815588.0,4830081.0,4841799.0,4852347.0,4863525.0,4874486.0,4887681.0,4903185.0
1,Alaska,58,58,58,7.91,7.92,7.92,Alaska,710231.0,710249.0,...,713910.0,722128.0,730443.0,737068.0,736283.0,737498.0,741456.0,739700.0,735139.0,731545.0
2,Arizona,183,136,129,2.51,1.89,1.77,Arizona,6392017.0,6392288.0,...,6407172.0,6472643.0,6554978.0,6632764.0,6730413.0,6829676.0,6941072.0,7044008.0,7158024.0,7278717.0
3,Arkansas,64,59,69,2.12,1.96,2.28,Arkansas,2915918.0,2916031.0,...,2921964.0,2940667.0,2952164.0,2959400.0,2967392.0,2978048.0,2989918.0,3001345.0,3009733.0,3017804.0
4,California,2111,1706,1750,5.35,4.32,4.46,California,37253956.0,37254519.0,...,37319502.0,37638369.0,37948800.0,38260787.0,38596972.0,38918045.0,39167117.0,39358497.0,39461588.0,39512223.0
5,Colorado,66,52,58,1.15,0.90,1.00,Colorado,5029196.0,5029319.0,...,5047349.0,5121108.0,5192647.0,5269035.0,5350101.0,5450623.0,5539215.0,5611885.0,5691287.0,5758736.0
6,Connecticut,67,54,54,1.88,1.50,1.50,Connecticut,3574097.0,3574147.0,...,3579114.0,3588283.0,3594547.0,3594841.0,3594524.0,3587122.0,3578141.0,3573297.0,3571520.0,3565287.0
7,Delaware,18,17,43,1.84,1.71,4.29,Delaware,897934.0,897937.0,...,899593.0,907381.0,915179.0,923576.0,932487.0,941252.0,948921.0,956823.0,965479.0,973764.0
8,District of Columbia,24,19,19,3.39,2.75,2.84,District of Columbia,601723.0,601767.0,...,605226.0,619800.0,634924.0,650581.0,662328.0,675400.0,685815.0,694906.0,701547.0,705749.0
9,Florida,558,412,499,2.60,1.91,2.29,Florida,18801310.0,18804564.0,...,18845537.0,19053237.0,19297822.0,19545621.0,19845911.0,20209042.0,20613477.0,20963613.0,21244317.0,21477737.0
10,Georgia,302,221,228,2.84,2.06,2.11,Georgia,9687653.0,9688729.0,...,9711881.0,9802431.0,9901430.0,9972479.0,10067278.0,10178447.0,10301890.0,10410330.0,10511131.0,10617423.0
11,Hawaii,99,92,106,6.99,6.34,7.35,Hawaii,1360301.0,1360307.0,...,1363963.0,1379329.0,1394804.0,1408243.0,1414538.0,1422052.0,1427559.0,1424393.0,1420593.0,1415872.0
12,Idaho,7,8,4,0.39,0.43,0.21,Idaho,1567582.0,1567657.0,...,1570746.0,1583910.0,1595324.0,1611206.0,1631112.0,1651059.0,1682380.0,1717715.0,1750536.0,1787065.0
13,Illinois,326,216,255,2.57,1.69,2.01,Illinois,12830632.0,12831572.0,...,12840503.0,12867454.0,12882510.0,12895129.0,12884493.0,12858913.0,12820527.0,12778828.0,12723071.0,12671821.0
14,Indiana,108,92,127,1.60,1.36,1.87,Indiana,6483802.0,6484051.0,...,6490432.0,6516528.0,6537703.0,6568713.0,6593644.0,6608422.0,6634304.0,6658078.0,6695497.0,6732219.0
15,Iowa,52,39,49,1.65,1.22,1.53,Iowa,3046355.0,3046871.0,...,3050745.0,3066336.0,3076190.0,3092997.0,3109350.0,3120960.0,3131371.0,3141550.0,3148618.0,3155070.0
16,Kansas,37,37,43,1.27,1.26,1.47,Kansas,2853118.0,2853123.0,...,2858190.0,2869225.0,2885257.0,2893212.0,2900475.0,2909011.0,2910844.0,2908718.0,2911359.0,2913314.0
17,Kentucky,66,67,57,1.48,1.49,1.26,Kentucky,4339367.0,4339333.0,...,4348181.0,4369821.0,4386346.0,4404659.0,4414349.0,4425976.0,4438182.0,4452268.0,4461153.0,4467673.0
18,Louisiana,88,99,86,1.89,2.13,1.86,Louisiana,4533372.0,4533487.0,...,4544532.0,4575625.0,4600972.0,4624527.0,4644013.0,4664628.0,4678135.0,4670560.0,4659690.0,4648794.0
19,Maine,18,17,14,1.34,1.25,1.02,Maine,1328361.0,1328358.0,...,1327629.0,1328284.0,1327729.0,1328009.0,1330513.0,1328262.0,1331317.0,1334612.0,1339057.0,1344212.0
20,Maryland,209,148,192,3.45,2.40,3.11,Maryland,5773552.0,5773794.0,...,5788645.0,5839419.0,5886992.0,5923188.0,5957283.0,5985562.0,6003323.0,6023868.0,6035802.0,6045680.0
21,Massachusetts,178,142,151,2.58,2.02,2.16,Massachusetts,6547629.0,6547785.0,...,6566307.0,6613583.0,6663005.0,6713315.0,6762596.0,6794228.0,6823608.0,6859789.0,6882635.0,6892503.0
22,Michigan,131,101,136,1.31,1.00,1.35,Michigan,9883640.0,9884116.0,...,9877510.0,9882412.0,9897145.0,9913065.0,9929848.0,9931715.0,9950571.0,9973114.0,9984072.0,9986857.0
23,Minnesota,148,117,134,2.62,2.05,2.35,Minnesota,5303925.0,5303927.0,...,5310828.0,5346143.0,5376643.0,5413479.0,5451079.0,5482032.0,5522744.0,5566230.0,5606249.0,5639632.0
24,Mississippi,58,41,45,1.95,1.39,1.53,Mississippi,2967297.0,2968130.0,...,2970548.0,2978731.0,2983816.0,2988711.0,2990468.0,2988471.0,2987938.0,2988510.0,2981020.0,2976149.0
25,Missouri,70,79,77,1.14,1.28,1.25,Missouri,5988927.0,5988950.0,...,5995974.0,6010275.0,6024367.0,6040715.0,6056202.0,6071732.0,6087135.0,6106670.0,6121623.0,6137428.0
26,Montana,2,4,3,0.19,0.37,0.27,Montana,989415.0,989407.0,...,990697.0,997316.0,1003783.0,1013569.0,1021869.0,1030475.0,1040859.0,1052482.0,1060665.0,1068778.0
27,Nebraska,17,33,22,0.88,1.68,1.12,Nebraska,1826341.0,1826305.0,...,1829542.0,1840672.0,1853303.0,1865279.0,1879321.0,1891277.0,1905616.0,1915947.0,1925614.0,1934408.0
28,Nevada,53,57,61,1.71,1.83,1.94,Nevada,2700551.0,2700677.0,...,2702405.0,2712730.0,2743996.0,2775970.0,2817628.0,2866939.0,2917563.0,2969905.0,3027341.0,3080156.0
29,New Hampshire,6,12,12,0.44,0.87,0.86,New Hampshire,1316470.0,1316462.0,...,1316762.0,1320202.0,1324232.0,1326622.0,1333341.0,1336350.0,1342307.0,1348787.0,1353465.0,1359711.0
30,New Jersey,310,245,279,3.49,2.64,3.01,New Jersey,8791894.0,8791978.0,...,8799446.0,8828117.0,8844942.0,8856972.0,8864525.0,8867949.0,8870827.0,8885525.0,8886025.0,8882190.0
31,New Mexico,41,29,24,1.95,1.37,1.13,New Mexico,2059179.0,2059199.0,...,2064552.0,2080450.0,2087309.0,2092273.0,2089568.0,2089291.0,2091630.0,2091784.0,2092741.0,2096829.0
32,New York,746,605,681,3.83,3.00,3.43,New York,19378102.0,19378144.0,...,19399878.0,19499241.0,19572932.0,19624447.0,19651049.0,19654666.0,19633428.0,19589572.0,19530351.0,19453561.0
33,North Carolina,185,159,178,1.76,1.52,1.69,North Carolina,9535483.0,9535751.0,...,9574323.0,9657592.0,9749476.0,9843336.0,9932887.0,10031646.0,10154788.0,10268233.0,10381615.0,10488084.0
34,North Dakota,18,10,15,2.36,1.28,1.94,North Dakota,672591.0,672576.0,...,674715.0,685225.0,701176.0,722036.0,737401.0,754066.0,754434.0,754942.0,758080.0,762062.0
35,Ohio,150,130,149,1.28,1.10,1.26,Ohio,11536504.0,11536751.0,...,11539336.0,11544663.0,11548923.0,11576684.0,11602700.0,11617527.0,11634370.0,11659650.0,11676341.0,11689100.0
36,Oklahoma,73,67,69,1.84,1.69,1.73,Oklahoma,3751351.0,3751582.0,...,3759944.0,3788379.0,3818814.0,3853214.0,3878187.0,3909500.0,3926331.0,3931316.0,3940235.0,3956971.0
37,Oregon,70,67,78,1.66,1.58,1.84,Oregon,3831074.0,3831079.0,...,3837491.0,3872036.0,3899001.0,3922468.0,3963244.0,4015792.0,4089976.0,4143625.0,4181886.0,4217737.0
38,Pennsylvania,199,156,166,1.55,1.20,1.28,Pennsylvania,12702379.0,12702868.0,...,12711160.0,12745815.0,12767118.0,12776309.0,12788313.0,12784826.0,12782275.0,12787641.0,12800922.0,12801989.0
39,Rhode Island,14,7,17,1.32,0.64,1.55,Rhode Island,1052567.0,1052964.0,...,1053959.0,1053649.0,1054621.0,1055081.0,1055936.0,1056065.0,1056770.0,1055673.0,1058287.0,1059361.0
40,South Carolina,80,67,88,1.55,1.31,1.70,South Carolina,4625364.0,4625366.0,...,4635649.0,4671994.0,4717354.0,4764080.0,4823617.0,4891938.0,4957968.0,5021268.0,5084156.0,5148714.0
41,South Dakota,16,16,12,1.80,1.80,1.34,South Dakota,814180.0,814198.0,...,816166.0,823579.0,833566.0,842316.0,849129.0,853988.0,862996.0,872868.0,878698.0,884659.0
42,Tennessee,129,113,85,1.89,1.63,1.22,Tennessee,6346105.0,6346276.0,...,6355311.0,6399291.0,6453898.0,6494340.0,6541223.0,6591170.0,6646010.0,6708799.0,6771631.0,6829174.0
43,Texas,1154,883,991,3.98,3.02,3.36,Texas,25145561.0,25146091.0,...,25241971.0,25645629.0,26084481.0,26480266.0,26964333.0,27470056.0,27914410.0,28295273.0,28628666.0,28995881.0
44,Utah,27,29,17,0.84,0.88,0.51,Utah,2763885.0,2763891.0,...,2775332.0,2814384.0,2853375.0,2897640.0,2936879.0,2981835.0,3041868.0,3101042.0,3153550.0,3205958.0
45,Vermont,4,3,2,0.64,0.47,0.31,Vermont,625741.0,625737.0,...,625879.0,627049.0,626090.0,626210.0,625214.0,625216.0,623657.0,624344.0,624358.0,623989.0
46,Virginia,191,169,161,2.23,1.96,1.86,Virginia,8001024.0,8001049.0,...,8023699.0,8101155.0,8185080.0,8252427.0,8310993.0,8361808.0,8410106.0,8463587.0,8501286.0,8535519.0
47,Washington,221,163,199,2.90,2.11,2.57,Washington,6724540.0,6724540.0,...,6742830.0,6826627.0,6897058.0,6963985.0,7054655.0,7163657.0,7294771.0,7423362.0,7523869.0,7614893.0
48,West Virginia,9,13,7,0.50,0.73,0.39,West Virginia,1852994.0,1853018.0,...,1854239.0,1856301.0,1856872.0,1853914.0,1849489.0,1842050.0,1831023.0,1817004.0,1804291.0,1792147.0
49,Wisconsin,51,35,66,0.88,0.59,1.12,Wisconsin,5686986.0,5687285.0,...,5690475.0,5705288.0,5719960.0,5736754.0,5751525.0,5760940.0,5772628.0,5790186.0,5807406.0,5822434.0
50,Wyoming,1,0,3,0.17,0.00,0.52,Wyoming,563626.0,563775.0,...,564487.0,567299.0,576305.0,582122.0,582531.0,585613.0,584215.0,578931.0,577601.0,578759.0

In [43]:
td_marge["Recompute TB Incidence 2019"]= td_marge['TB case 2019']/td_marge['2019_y']*100000
td_marge

,U.S. jurisdiction,TB case 2019,TB case 2020,TB case 2021,TB incidence 2019,TB incidence 2020,TB incidence 2021,Geographic Area_x,Census_x,Estimates Base_x,...,2011_y,2012_y,2013_y,2014_y,2015_y,2016_y,2017_y,2018_y,2019_y,Recompute TB Incidence 2019
0,Alabama,87,72,92,1.77,1.43,1.83,Alabama,4779736.0,4780125.0,...,4799069.0,4815588.0,4830081.0,4841799.0,4852347.0,4863525.0,4874486.0,4887681.0,4903185.0,1.774357
1,Alaska,58,58,58,7.91,7.92,7.92,Alaska,710231.0,710249.0,...,722128.0,730443.0,737068.0,736283.0,737498.0,741456.0,739700.0,735139.0,731545.0,7.928425
2,Arizona,183,136,129,2.51,1.89,1.77,Arizona,6392017.0,6392288.0,...,6472643.0,6554978.0,6632764.0,6730413.0,6829676.0,6941072.0,7044008.0,7158024.0,7278717.0,2.514179
3,Arkansas,64,59,69,2.12,1.96,2.28,Arkansas,2915918.0,2916031.0,...,2940667.0,2952164.0,2959400.0,2967392.0,2978048.0,2989918.0,3001345.0,3009733.0,3017804.0,2.120747
4,California,2111,1706,1750,5.35,4.32,4.46,California,37253956.0,37254519.0,...,37638369.0,37948800.0,38260787.0,38596972.0,38918045.0,39167117.0,39358497.0,39461588.0,39512223.0,5.342651
5,Colorado,66,52,58,1.15,0.90,1.00,Colorado,5029196.0,5029319.0,...,5121108.0,5192647.0,5269035.0,5350101.0,5450623.0,5539215.0,5611885.0,5691287.0,5758736.0,1.146085
6,Connecticut,67,54,54,1.88,1.50,1.50,Connecticut,3574097.0,3574147.0,...,3588283.0,3594547.0,3594841.0,3594524.0,3587122.0,3578141.0,3573297.0,3571520.0,3565287.0,1.879232
7,Delaware,18,17,43,1.84,1.71,4.29,Delaware,897934.0,897937.0,...,907381.0,915179.0,923576.0,932487.0,941252.0,948921.0,956823.0,965479.0,973764.0,1.848497
8,District of Columbia,24,19,19,3.39,2.75,2.84,District of Columbia,601723.0,601767.0,...,619800.0,634924.0,650581.0,662328.0,675400.0,685815.0,694906.0,701547.0,705749.0,3.400642
9,Florida,558,412,499,2.60,1.91,2.29,Florida,18801310.0,18804564.0,...,19053237.0,19297822.0,19545621.0,19845911.0,20209042.0,20613477.0,20963613.0,21244317.0,21477737.0,2.598039
10,Georgia,302,221,228,2.84,2.06,2.11,Georgia,9687653.0,9688729.0,...,9802431.0,9901430.0,9972479.0,10067278.0,10178447.0,10301890.0,10410330.0,10511131.0,10617423.0,2.844381
11,Hawaii,99,92,106,6.99,6.34,7.35,Hawaii,1360301.0,1360307.0,...,1379329.0,1394804.0,1408243.0,1414538.0,1422052.0,1427559.0,1424393.0,1420593.0,1415872.0,6.992157
12,Idaho,7,8,4,0.39,0.43,0.21,Idaho,1567582.0,1567657.0,...,1583910.0,1595324.0,1611206.0,1631112.0,1651059.0,1682380.0,1717715.0,1750536.0,1787065.0,0.391704
13,Illinois,326,216,255,2.57,1.69,2.01,Illinois,12830632.0,12831572.0,...,12867454.0,12882510.0,12895129.0,12884493.0,12858913.0,12820527.0,12778828.0,12723071.0,12671821.0,2.572637
14,Indiana,108,92,127,1.60,1.36,1.87,Indiana,6483802.0,6484051.0,...,6516528.0,6537703.0,6568713.0,6593644.0,6608422.0,6634304.0,6658078.0,6695497.0,6732219.0,1.604226
15,Iowa,52,39,49,1.65,1.22,1.53,Iowa,3046355.0,3046871.0,...,3066336.0,3076190.0,3092997.0,3109350.0,3120960.0,3131371.0,3141550.0,3148618.0,3155070.0,1.648141
16,Kansas,37,37,43,1.27,1.26,1.47,Kansas,2853118.0,2853123.0,...,2869225.0,2885257.0,2893212.0,2900475.0,2909011.0,2910844.0,2908718.0,2911359.0,2913314.0,1.270031
17,Kentucky,66,67,57,1.48,1.49,1.26,Kentucky,4339367.0,4339333.0,...,4369821.0,4386346.0,4404659.0,4414349.0,4425976.0,4438182.0,4452268.0,4461153.0,4467673.0,1.477279
18,Louisiana,88,99,86,1.89,2.13,1.86,Louisiana,4533372.0,4533487.0,...,4575625.0,4600972.0,4624527.0,4644013.0,4664628.0,4678135.0,4670560.0,4659690.0,4648794.0,1.892964
19,Maine,18,17,14,1.34,1.25,1.02,Maine,1328361.0,1328358.0,...,1328284.0,1327729.0,1328009.0,1330513.0,1328262.0,1331317.0,1334612.0,1339057.0,1344212.0,1.339074
20,Maryland,209,148,192,3.45,2.40,3.11,Maryland,5773552.0,5773794.0,...,5839419.0,5886992.0,5923188.0,5957283.0,5985562.0,6003323.0,6023868.0,6035802.0,6045680.0,3.457014
21,Massachusetts,178,142,151,2.58,2.02,2.16,Massachusetts,6547629.0,6547785.0,...,6613583.0,6663005.0,6713315.0,6762596.0,6794228.0,6823608.0,6859789.0,6882635.0,6892503.0,2.582516
22,Michigan,131,101,136,1.31,1.00,1.35,Michigan,9883640.0,9884116.0,...,9882412.0,9897145.0,9913065.0,9929848.0,9931715.0,9950571.0,9973114.0,9984072.0,9986857.0,1.311724
23,Minnesota,148,117,134,2.62,2.05,2.35,Minnesota,5303925.0,5303927.0,...,5346143.0,5376643.0,5413479.0,5451079.0,5482032.0,5522744.0,5566230.0,5606249.0,5639632.0,2.624285
24,Mississippi,58,41,45,1.95,1.39,1.53,Mississippi,2967297.0,2968130.0,...,2978731.0,2983816.0,2988711.0,2990468.0,2988471.0,2987938.0,2988510.0,2981020.0,2976149.0,1.948827
25,Missouri,70,79,77,1.14,1.28,1.25,Missouri,5988927.0,5988950.0,...,6010275.0,6024367.0,6040715.0,6056202.0,6071732.0,6087135.0,6106670.0,6121623.0,6137428.0,1.140543
26,Montana,2,4,3,0.19,0.37,0.27,Montana,989415.0,989407.0,...,997316.0,1003783.0,1013569.0,1021869.0,1030475.0,1040859.0,1052482.0,1060665.0,1068778.0,0.187130
27,Nebraska,17,33,22,0.88,1.68,1.12,Nebraska,1826341.0,1826305.0,...,1840672.0,1853303.0,1865279.0,1879321.0,1891277.0,1905616.0,1915947.0,1925614.0,1934408.0,0.878822
28,Nevada,53,57,61,1.71,1.83,1.94,Nevada,2700551.0,2700677.0,...,2712730.0,2743996.0,2775970.0,2817628.0,2866939.0,2917563.0,2969905.0,3027341.0,3080156.0,1.720692
29,New Hampshire,6,12,12,0.44,0.87,0.86,New Hampshire,1316470.0,1316462.0,...,1320202.0,1324232.0,1326622.0,1333341.0,1336350.0,1342307.0,1348787.0,1353465.0,1359711.0,0.441270
30,New Jersey,310,245,279,3.49,2.64,3.01,New Jersey,8791894.0,8791978.0,...,8828117.0,8844942.0,8856972.0,8864525.0,8867949.0,8870827.0,8885525.0,8886025.0,8882190.0,3.490130
31,New Mexico,41,29,24,1.95,1.37,1.13,New Mexico,2059179.0,2059199.0,...,2080450.0,2087309.0,2092273.0,2089568.0,2089291.0,2091630.0,2091784.0,2092741.0,2096829.0,1.955334
32,New York,746,605,681,3.83,3.00,3.43,New York,19378102.0,19378144.0,...,19499241.0,19572932.0,19624447.0,19651049.0,19654666.0,19633428.0,19589572.0,19530351.0,19453561.0,3.834773
33,North Carolina,185,159,178,1.76,1.52,1.69,North Carolina,9535483.0,9535751.0,...,9657592.0,9749476.0,9843336.0,9932887.0,10031646.0,10154788.0,10268233.0,10381615.0,10488084.0,1.763907
34,North Dakota,18,10,15,2.36,1.28,1.94,North Dakota,672591.0,672576.0,...,685225.0,701176.0,722036.0,737401.0,754066.0,754434.0,754942.0,758080.0,762062.0,2.362013
35,Ohio,150,130,149,1.28,1.10,1.26,Ohio,11536504.0,11536751.0,...,11544663.0,11548923.0,11576684.0,11602700.0,11617527.0,11634370.0,11659650.0,11676341.0,11689100.0,1.283247
36,Oklahoma,73,67,69,1.84,1.69,1.73,Oklahoma,3751351.0,3751582.0,...,3788379.0,3818814.0,3853214.0,3878187.0,3909500.0,3926331.0,3931316.0,3940235.0,3956971.0,1.844845
37,Oregon,70,67,78,1.66,1.58,1.84,Oregon,3831074.0,3831079.0,...,3872036.0,3899001.0,3922468.0,3963244.0,4015792.0,4089976.0,4143625.0,4181886.0,4217737.0,1.659658
38,Pennsylvania,199,156,166,1.55,1.20,1.28,Pennsylvania,12702379.0,12702868.0,...,12745815.0,12767118.0,12776309.0,12788313.0,12784826.0,12782275.0,12787641.0,12800922.0,12801989.0,1.554446
39,Rhode Island,14,7,17,1.32,0.64,1.55,Rhode Island,1052567.0,1052964.0,...,1053649.0,1054621.0,1055081.0,1055936.0,1056065.0,1056770.0,1055673.0,1058287.0,1059361.0,1.321551
40,South Carolina,80,67,88,1.55,1.31,1.70,South Carolina,4625364.0,4625366.0,...,4671994.0,4717354.0,4764080.0,4823617.0,4891938.0,4957968.0,5021268.0,5084156.0,5148714.0,1.553786
41,South Dakota,16,16,12,1.80,1.80,1.34,South Dakota,814180.0,814198.0,...,823579.0,833566.0,842316.0,849129.0,853988.0,862996.0,872868.0,878698.0,884659.0,1.808606
42,Tennessee,129,113,85,1.89,1.63,1.22,Tennessee,6346105.0,6346276.0,...,6399291.0,6453898.0,6494340.0,6541223.0,6591170.0,6646010.0,6708799.0,6771631.0,6829174.0,1.888955
43,Texas,1154,883,991,3.98,3.02,3.36,Texas,25145561.0,25146091.0,...,25645629.0,26084481.0,26480266.0,26964333.0,27470056.0,27914410.0,28295273.0,28628666.0,28995881.0,3.979876
44,Utah,27,29,17,0.84,0.88,0.51,Utah,2763885.0,2763891.0,...,2814384.0,2853375.0,2897640.0,2936879.0,2981835.0,3041868.0,3101042.0,3153550.0,3205958.0,0.842182
45,Vermont,4,3,2,0.64,0.47,0.31,Vermont,625741.0,625737.0,...,627049.0,626090.0,626210.0,625214.0,625216.0,623657.0,624344.0,624358.0,623989.0,0.641037
46,Virginia,191,169,161,2.23,1.96,1.86,Virginia,8001024.0,8001049.0,...,8101155.0,8185080.0,8252427.0,8310993.0,8361808.0,8410106.0,8463587.0,8501286.0,8535519.0,2.237708
47,Washington,221,163,199,2.90,2.11,2.57,Washington,6724540.0,6724540.0,...,6826627.0,6897058.0,6963985.0,7054655.0,7163657.0,7294771.0,7423362.0,7523869.0,7614893.0,2.902208
48,West Virginia,9,13,7,0.50,0.73,0.39,West Virginia,1852994.0,1853018.0,...,1856301.0,1856872.0,1853914.0,1849489.0,1842050.0,1831023.0,1817004.0,1804291.0,1792147.0,0.502191
49,Wisconsin,51,35,66,0.88,0.59,1.12,Wisconsin,5686986.0,5687285.0,...,5705288.0,5719960.0,5736754.0,5751525.0,5760940.0,5772628.0,5790186.0,5807406.0,5822434.0,0.875922
50,Wyoming,1,0,3,0.17,0.00,0.52,Wyoming,563626.0,563775.0,...,567299.0,576305.0,582122.0,582531.0,585613.0,584215.0,578931.0,577601.0,578759.0,0.172783